<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Interfold.IntegrationTests" />
    <InternalsVisibleTo Include="Interfold.Infrastructure.Scylla" />
    <InternalsVisibleTo Include="Interfold.Infrastructure.InMemory" />
    <InternalsVisibleTo Include="Interfold.Infrastructure.Postgres" />
    <ProjectReference Include="..\..\shared\Interfold.Domain\Interfold.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CassandraCSharpDriver" />
    <PackageReference Include="FirebaseAdmin" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Polly.Core" />
  </ItemGroup>
</Project>